
// FIXED BY AI: No hooks used, so no 'use client' needed
import { Nav } from '@/components/nav';
import { Footer } from '@/components/footer';
import { Button } from '@/components/button';
import { LiveScan } from '@/components/live-scan';
import { CodeBlock } from '@/components/code-block';
import { FeatureVisual } from '@/components/feature-visual';
import { ScrollReveal } from '@/components/scroll-reveal';
import { CipherText } from '@/components/cipher-text';
import { ThreatTicker } from '@/components/threat-ticker';
import { CapabilitiesGrid } from '@/components/capabilities-grid';
import { GlitchText } from '@/components/glitch-text';
import { KonamiEgg } from '@/components/konami-egg';
import { MatrixRain } from '@/components/matrix-rain';
import Image from 'next/image';
import { ArrowRight } from 'lucide-react';

const headersCode = `// Generated by Barracade for Next.js
const securityHeaders = [
  {
    key: 'Content-Security-Policy',
    value: "default-src 'self'; script-src 'self'"
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload'
  },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'X-Frame-Options', value: 'DENY' },
];`;

 export default function Page() {
  return (
    <>
      {/* barracade://initiate -- QlJDRC1TRUMtU1RBUlQ6IC9zZWN1cml0eS9sb2dzL2FyY2hpdmU= */}
      <Nav />
      <KonamiEgg />
      <main>
        {/* Hero - image pinned to right+top, text overlays */}
        <section className="min-h-screen relative overflow-hidden">
          <MatrixRain />
          {/* Hero image */}
          <div className="absolute top-0 right-0 w-[65%] h-full hidden lg:block pointer-events-none">
            <div className="absolute inset-0 bg-gradient-to-r from-[#050505] via-[#050505]/60 to-transparent z-10" />
            <div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-transparent to-transparent z-10" />
            <Image
              src="/hero-face.png"
              alt=""
              fill
              className="object-cover object-[70%_15%] invert opacity-90 select-none scale-110"
              priority
            />
          </div>
          {/* Text content overlaid */}
          <div className="relative z-20 min-h-screen flex items-center">
            <div className="mx-auto max-w-6xl px-6 w-full py-32">
              <div className="max-w-xl">
                <ScrollReveal>
                  <GlitchText
                    as="h1"
                    className="text-4xl font-medium tracking-tight text-white sm:text-5xl lg:text-[3.25rem] leading-[1.12]"
                  >
                    Security for your entire stack
                  </GlitchText>
                </ScrollReveal>
                <ScrollReveal delay={0.1}>
                  <p className="mt-6 text-[15px] text-neutral-500 leading-relaxed max-w-md">
                    Website scanning, runtime protection, code analysis, compliance
                    reporting. A desktop app you install once and keep forever.
                  </p>
                </ScrollReveal>
                <ScrollReveal delay={0.15}>
                  <div className="mt-4 font-mono text-[12px] text-neutral-600">
                    Desktop app for Windows, macOS, and Linux
                  </div>
                </ScrollReveal>
                <ScrollReveal delay={0.2}>
                  <div className="mt-8 flex gap-3">
                    <Button href="/purchase" size="lg">
                      Purchase <ArrowRight className="h-3.5 w-3.5" />
                    </Button>
                    <Button href="/features" variant="secondary" size="lg">
                      Features
                    </Button>
                  </div>
                </ScrollReveal>
                <ScrollReveal delay={0.3}>
                  <div className="mt-12">
                    <CipherText
                      encrypted="5365637572697479206973206e6f742061206665617475726521"
                      decrypted="BRCD-H3X-4C71V4T3D"
                      hint="Hex encoded - click to decode"
                    />
                  </div>
                </ScrollReveal>
              </div>
            </div>
          </div>
        </section>
        {/* Threat counter */}
        <section className="py-20 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6 flex flex-col sm:flex-row sm:items-end sm:justify-between gap-8">
            <ScrollReveal>
              <ThreatTicker />
            </ScrollReveal>
            <ScrollReveal delay={0.1}>
              <CipherText
                encrypted="01000010 01010010 01000011 01000100"
                decrypted="BRCD-B1N4RY-D3C0D3"
                hint="Binary - click to decode"
              />
            </ScrollReveal>
          </div>
        </section>
        {/* Terminal demo - interactive */}
        <section className="py-32 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6">
            <div className="grid lg:grid-cols-[1fr,1.2fr] gap-16 items-start">
              <ScrollReveal>
                <div>
                  <h2 className="text-2xl font-medium text-white tracking-tight mb-4">
                    Scan any website
                  </h2>
                  <p className="text-[14px] text-neutral-500 leading-relaxed mb-6">
                    Point Barracade at any public URL and get a full security audit
                    in seconds. It checks headers, TLS config, cookies, exposed
                    endpoints, and CMS-specific issues. You get a letter grade and
                    a list of things to fix.
                  </p>
                  <p className="text-[13px] text-emerald-900 leading-relaxed font-mono">
                    Try it. Type any URL in the terminal.
                  </p>
                </div>
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <LiveScan />
              </ScrollReveal>
            </div>
          </div>
        </section>
        {/* Headers Generator */}
        <section className="py-32 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6">
            <div className="grid lg:grid-cols-[1.2fr,1fr] gap-16 items-start">
              <ScrollReveal>
                <CodeBlock
                  code={headersCode}
                  filename="next.config.ts"
                />
              </ScrollReveal>
              <ScrollReveal delay={0.1}>
                <div>
                  <h2 className="text-2xl font-medium text-white tracking-tight mb-4">
                    Generate security headers
                  </h2>
                  <p className="text-[14px] text-neutral-500 leading-relaxed mb-4">
                    Pick the headers you need and Barracade generates deployment-ready
                    config for your platform. Supports Next.js, Vercel, Netlify,
                    Express, Nginx, Apache, and more.
                  </p>
                  <p className="text-[13px] text-neutral-600 leading-relaxed mb-6">
                    CSP, HSTS, X-Frame-Options, Permissions-Policy, Referrer-Policy.
                    Copy and paste straight into your project.
                  </p>
                  <CipherText
                    encrypted="QlJDRC1CNjQtUjBPVEtJVA=="
                    decrypted="BRCD-B64-R00TK1T"
                    hint="Base64 - click to decode"
                  />
                </div>
              </ScrollReveal>
            </div>
          </div>
        </section>
        {/* Dashboard mock */}
        <section className="py-32 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6">
            <ScrollReveal>
              <div className="mb-12">
                <h2 className="text-2xl font-medium text-white tracking-tight mb-4">
                  Everything in one place
                </h2>
                <p className="text-[14px] text-neutral-500 max-w-lg leading-relaxed">
                  Threats, incidents, compliance, analytics. One dashboard that
                  gives you the full picture without jumping between tools.
                </p>
              </div>
            </ScrollReveal>
            <ScrollReveal delay={0.1}>
              <div className="grid sm:grid-cols-2 gap-4">
                <FeatureVisual type="rasp" />
                <FeatureVisual type="compliance" />
              </div>
            </ScrollReveal>
          </div>
        </section>
        {/* Capabilities - interactive cards */}
        <section className="py-32 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6">
            <ScrollReveal>
              <h2 className="text-2xl font-medium text-white tracking-tight mb-4">
                What you get
              </h2>
              <p className="text-[13px] text-neutral-600 mb-16">
                Hover over each card for details.
              </p>
            </ScrollReveal>
            <CapabilitiesGrid />
          </div>
        </section>
        {/* Secret section */}
        <section className="py-16 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6">
            <ScrollReveal>
              <div className="flex flex-wrap gap-x-12 gap-y-4">
                <CipherText
                  encrypted="Uif!cbssjfs!qspufdut"
                  decrypted="BRCD-C4354R-SH1FT"
                  hint="Caesar cipher +1 - click to decode"
                />
                <CipherText
                  encrypted="2e 2e 2f 73 65 63 72 65 74"
                  decrypted="BRCD-P4TH-TR4V3RS4L"
                  hint="Hex bytes - click to decode"
                />
                <CipherText
                  encrypted="&#x25;42&#x25;52&#x25;43&#x25;44"
                  decrypted="BRCD-URL-3NC0D3D"
                  hint="URL encoded - click to decode"
                />
              </div>
            </ScrollReveal>
          </div>
        </section>
        {/* CTA */}
        <section className="py-32 border-t border-white/[0.04]">
          <div className="mx-auto max-w-6xl px-6">
            <ScrollReveal>
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-8">
                <div>
                  <h2 className="text-xl font-medium text-white mb-2">$69.99, once. No subscriptions.</h2>
                  <p className="text-[14px] text-neutral-600">Lifetime license. Every future update included.</p>
                </div>
                <Button href="/purchase" size="lg">
                  Purchase <ArrowRight className="h-3.5 w-3.5" />
                </Button>
              </div>
            </ScrollReveal>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
