import { Nav } from '@/components/nav';
import { Footer } from '@/components/footer';
import { FeatureVisual } from '@/components/feature-visual';
import { ScrollReveal } from '@/components/scroll-reveal';
import { CodeBlock } from '@/components/code-block';
import { CipherText } from '@/components/cipher-text';
import { GlitchText } from '@/components/glitch-text';
import { Button } from '@/components/button';
import { ArrowRight } from 'lucide-react';

const features: {
  title: string;
  description: string;
  detail: string;
  visual: 'scanner' | 'siteHealth' | 'headers' | 'rasp' | 'defense' | 'sast' | 'compliance' | 'dependencies';
  code?: string;
  codeFilename?: string;
  cipher?: { encrypted: string; decrypted: string; hint: string };
}[] = [
  {
    title: 'Website Scanner',
    description: 'Run a full security audit on any public URL. Barracade checks headers, TLS, cookies, exposed endpoints, and CMS-specific issues. You get a letter grade from A to F and a list of what to fix.',
    detail: 'Supports batch scanning and grade tracking over time so you can see if deployments introduce regressions.',
    visual: 'scanner',
  },
  {
    title: 'Site Health',
    description: 'Monitor multiple sites from one dashboard. Track security grades over time and get alerts when something degrades.',
    detail: 'Set grade thresholds per domain. If a deploy drops your grade, you know about it.',
    visual: 'siteHealth',
    cipher: { encrypted: 'R3JhZGUgQSs=', decrypted: 'BRCD-H34LTH-A+', hint: 'Base64 grade' },
  },
  {
    title: 'Headers Generator',
    description: 'Pick the security headers you need and get deployment-ready config for your stack. Supports Next.js, Vercel, Netlify, Express, Nginx, Apache, and more.',
    detail: 'Covers CSP, HSTS, X-Frame-Options, Permissions-Policy, and Referrer-Policy. Copy the output straight into your project.',
    visual: 'headers',
    code: `// Generated by Barracade for Next.js
const securityHeaders = [
  { key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains' },
  { key: 'X-Content-Type-Options',  value: 'nosniff' },
  { key: 'X-Frame-Options',         value: 'DENY' },
  { key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin' },
];`,
    codeFilename: 'next.config.ts',
  },
  {
    title: 'RASP Engine',
    description: 'Runtime protection that catches SQL injection, XSS, SSRF, command injection, path traversal, prototype pollution, NoSQL injection, header injection, and open redirects.',
    detail: 'Detects attacks at the application layer. You can tune sensitivity per route.',
    visual: 'rasp',
    cipher: { encrypted: '53514c693b2044524f50205441424c45', decrypted: 'BRCD-1NJ3CT10N-BL0CK3D', hint: 'Hex - SQL injection blocked' },
  },
  {
    title: 'Defense Engine',
    description: 'Policy-based threat response. Set rules for what happens when an attack is detected: block, throttle, isolate, or alert. Every action is logged.',
    detail: 'Define your own policies or use the defaults. Full audit trail for every decision the engine makes.',
    visual: 'defense',
  },
  {
    title: 'Static Analysis (SAST)',
    description: 'Scan your source code for vulnerabilities across 8 languages. Finds hardcoded secrets, unsafe deserialization, injection risks, and more.',
    detail: 'Results include file paths, line numbers, and severity ratings so you can prioritize fixes.',
    visual: 'sast',
  },
  {
    title: 'Compliance',
    description: 'Map your security posture against CIS, PCI-DSS, HIPAA, and SOC 2 frameworks. See which controls you meet and where the gaps are.',
    detail: 'Export audit-ready reports. Track remediation progress per framework.',
    visual: 'compliance',
  },
  {
    title: 'Dependencies and SBOM',
    description: 'Generate a software bill of materials. Track known CVEs across your dependency tree, flag typosquat packages, and audit licenses.',
    detail: 'See exactly which packages are vulnerable and what versions fix them.',
    visual: 'dependencies',
    cipher: { encrypted: 'cmlzay5zY29yZSA9IDk3', decrypted: 'BRCD-P0STUR3-97', hint: 'Base64 risk score' },
  },
];

export default function FeaturesPage() {
  // FIXED BY AI: Fragments and JSX are balanced. No hooks used, so no 'use client' needed.
  return (
    <>
      <Nav />
      <main className="pt-32 pb-20">
        <div className="mx-auto max-w-6xl px-6 mb-24">
          <ScrollReveal>
            <GlitchText
              as="h1"
              className="text-4xl font-medium tracking-tight text-white sm:text-5xl"
            >
              Features
            </GlitchText>
          </ScrollReveal>
          <ScrollReveal delay={0.1}>
            <p className="mt-6 text-[15px] text-neutral-500 max-w-lg leading-relaxed">
              Everything Barracade ships with. One desktop app that handles
              scanning, protection, code analysis, compliance, and monitoring.
            </p>
          </ScrollReveal>
          <ScrollReveal delay={0.15}>
            <p className="mt-3 text-[11px] text-emerald-900/50 font-mono">
              Hidden codes are scattered across this page. Can you find them all?
            </p>
          </ScrollReveal>
        </div>

        <div className="mx-auto max-w-6xl px-6 space-y-32">
          {features.map((feat, i) => (
            <ScrollReveal key={feat.title} delay={0.05}>
              <div className="grid gap-12 lg:grid-cols-2 items-start">
                <div className={i % 2 === 1 ? 'lg:order-2' : ''}>
                  <h2 className="text-lg font-medium text-neutral-200 mb-3">{feat.title}</h2>
                  <p className="text-[14px] text-neutral-500 leading-relaxed mb-3">{feat.description}</p>
                  <p className="text-[13px] text-neutral-600 leading-relaxed">{feat.detail}</p>
                  {feat.code && (
                    <div className="mt-6">
                      <CodeBlock code={feat.code} filename={feat.codeFilename} />
                    </div>
                  )}
                  {feat.cipher && (
                    <div className="mt-4">
                      <CipherText
                        encrypted={feat.cipher.encrypted}
                        decrypted={feat.cipher.decrypted}
                        hint={feat.cipher.hint}
                      />
                    </div>
                  )}
                </div>
                <div className={i % 2 === 1 ? 'lg:order-1' : ''}>
                  <FeatureVisual type={feat.visual} />
                </div>
              </div>
            </ScrollReveal>
          ))}
        </div>

        {/* Hidden cipher row */}
        <div className="mx-auto max-w-6xl px-6 mt-20">
          <ScrollReveal>
            <div className="flex flex-wrap gap-x-10 gap-y-3">
              <CipherText
                encrypted="6665617475726573.756e6c6f636b6564"
                decrypted="BRCD-F34TUR3S-UNL0CK3D"
                hint="Hex dotted - click to decode"
              />
              <CipherText
                encrypted="01011010 01000101 01010010 01001111"
                decrypted="BRCD-Z3R0-D4Y-FR33"
                hint="Binary - zero day"
              />
            </div>
          </ScrollReveal>
        </div>

        <div className="mx-auto max-w-6xl px-6 mt-32 pt-20 border-t border-white/[0.04]">
          <ScrollReveal>
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-8">
              <div>
                <h2 className="text-xl font-medium text-white mb-2">$69.99, once. Lifetime license.</h2>
                <p className="text-[14px] text-neutral-600">Every future update included.</p>
              </div>
              <Button href="/purchase" size="lg">
                Purchase <ArrowRight className="h-3.5 w-3.5" />
              </Button>
            </div>
          </ScrollReveal>
        </div>
      </main>
      <Footer />
    </>
  );
}